apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080